remote_theme: just-the-docs/just-the-docs

title: Systems Card Game
description: A participatory tool for mapping systems and exploring change

url: https://hmatthes.github.io
baseurl: /systems-card-game

nav_enabled: true
search_enabled: true

aux_links:
  "View on GitHub":
    - "https://github.com/hmatthes/systems-card-game"

aux_links_new_tab: true
color_scheme: light